version: '3.8'

services:
  # Redis Database
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev-network

  # RedisInsight - Interface Gráfica para Redis
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight-dev
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    environment:
      - RIPORT=5540
    networks:
      - dev-network

volumes:
  redis_data:
    driver: local
  redis_insight_data:
    driver: local

networks:
  dev-network:
    driver: bridge