spring:
  application:
    name: fidc-sistema-core-simulator

  profiles:
    active: local

server:
  port: 8081

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    try-it-out-enabled: true
